#!/usr/bin/env bash
# a bash script to configure Nginx server to redirect to another page
sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World" | sudo tee /var/www/html/index.html
replacement="server_name _;\n\trewrite ^/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s#server_name _;#$replacement#" /etc/nginx/sites-available/default

sudo service nginx restart
