#!/usr/bin/env bash
# a bash script to configure Nginx server to redirect to another page
sudo apt-get update
sudo apt-get -y install nginx

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
replacement="server_name _;\n\trewrite ^/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\root \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s#server_name _;#$replacement#" /etc/nginx/sites-available/default

sudo service nginx restart
