#!/usr/bin/env bash
# a script that configure a ubuntu

sudo apt update
sudo apt -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

host=$(hostname)

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
replacement="server_name _;\n\tadd_header X-Served-By $host;\n\trewrite ^/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;\n\terror_page 404 \/404.html;\n\tlocation \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s#server_name _;#$replacement#" /etc/nginx/sites-available/default
sudo service nginx restart
