#!/usr/bin/env bash
# installation and configuration of HAproxy (load balancer)

sudo apt install
sudo apt -y install haproxy

echo "
frontend rash_http
	bind *:80
	mode http
	default_backend rash_backend
	
backend rash_backend
	balance roundrobin
	server 285293-web-01 35.174.208.242:80 check
	server 285293-web-02 54.162.47.71:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
