#!/usr/bin/env bash
# a script that generates a MySQL dump and creates a compressed archive
if [ $# -ne 1 ]; then
        exit 1
fi
passwd="$1"
current=$(date +'%d-%m-%Y')
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czf "$current".tar.gz backup.sql
