#!/usr/bin/env bash
# a bash script that configures a server to listen to port 80
sudo sed -i "s#8080#80#" /etc/nginx/sites-enabled/default
sudo service nginx start
kill -9 "$(cat /var/run/nginx.pid)"
