#!/usr/bin/env bash
# a bash script that displays To infinity and beyond indefinitely
delay=2
on_signal() {
	echo "I am invincible!!!"
}
trap 'on_signal' SIGTERM SIGINT
while true; do
	echo "To infinity and beyond"
	sleep "$delay"
done
