#!/usr/bin/env bash
# a bash script that displays the content of a file
files=$(ls /etc/passwd)
while IFS=: read -r username x uid gid gecos homedir shell; do
	echo "$username:$uid:$homedir"
done < "$files"
