#!/usr/bin/env bash
# a script that display a message but for the 9th iteration print hi
count=1
while [[ "$count" -le 10 ]]; do
	echo "Best School"
	if [ "$count" -eq 9 ]; then
		echo "Hi"
	fi
	count=$((count + 1))
done
