#!/usr/bin/env bash
# a script that configures an ubuntu server
sudo echo '8.8.8.8	facebook.com' | tee -a /etc/hosts
sed -i 's/127.*$/127.0.0.2 localhost\n/' /etc/hosts > ~/hosts.new
cat ~/hosts.new > /etc/hosts
